### ISSUE TITLE
fivem errors

### ISSUE THREAD

**Issue by hujekmujek** [Rimmuru/Gta5-Mods-Lua-Loader#3]
https://github.com/Rimmuru/Gta5-Mods-Lua-Loader/assets/155384494/c1a89f60-86ef-4f07-ba5c-f29887832fec

So i installed mod correctly but as u can see whenever i try to run any mod i get fivem error.

**Comment by Rimmuru** [comment]
Should be fixed. Writing code on phone isn’t great fun

**Comment by hujekmujek** [comment]
https://github.com/Rimmuru/Gta5-Mods-Lua-Loader/assets/155384494/34ea57a4-cb09-4737-9418-b387946649b7

Nope, every mod still gives this error

**Comment by Rimmuru** [comment]
My bad, missed an _

**Comment by hujekmujek** [comment]
Now it works perfectly fine, ty.
