### ISSUE TITLE
request

### ISSUE THREAD

**Issue by hujekmujek** [Rimmuru/Gta5-Mods-Lua-Loader#5]
https://github.com/Rimmuru/Gta5-Mods-Lua-Loader/assets/155384494/350cac3f-4d97-49da-b958-ea2621d1c7bb
https://www.gta5-mods.com/scripts/mount-mod

is it possible for this to work?

**Comment by Rimmuru** [comment]
looking into it as soon my gta decides to work

**Comment by Rimmuru** [comment]
should be fixed :)

**Comment by hujekmujek** [comment]
Alr i will check it as soon as i get home and let u know

**Comment by hujekmujek** [comment]
so it doesnt give error when i run this but when i try to mount any ped it give me this:
https://github.com/Rimmuru/Gta5-Mods-Lua-Loader/assets/155384494/02604ed7-bb1d-438a-8565-25a671741bff

**Comment by Rimmuru** [comment]
i swear.. i hate pointers in natives

**Comment by Rimmuru** [comment]
download from main branch

**Comment by hujekmujek** [comment]
now it's loading but nothing happens when im trying to open menu or just ride pet

**Comment by Rimmuru** [comment]
issue appears to be with the mod itself it is from 2015 after all. i rebuilt the function still doesnt let you mount it. others in the comments of the post have said the same too
![chrome_jFaMGQOqkO](https://github.com/Rimmuru/Gta5-Mods-Lua-Loader/assets/81404937/143f1ddf-4256-44df-888e-75f9dcc34b0c)

**Comment by hujekmujek** [comment]
Well thats sad, thanks for trying anyway
